import type { ServiceData } from "./services-data";

export type IndustryData = ServiceData;

export const industries: IndustryData[] = [
  {
    slug: "ai-automation-in-e-commerce",
    title: "Scale E-Commerce with AI Automation",
    subtitle: "Running an online store is overwhelming when every order, update, and customer message depends on manual effort.",
    description:
      "AI automation helps you sell more while working less. We build end-to-end automation systems for ecommerce brands -from abandoned cart recovery to inventory sync, AI chatbots to personalised marketing -so your store runs itself while you focus on growth.",
    heroTag: "E-Commerce Automation",
    stats: [
      { value: "35%", label: "Abandoned cart recovery rate" },
      { value: "25%", label: "Reduction in order errors" },
      { value: "30%", label: "Increase in customer retention" },
      { value: "50+hrs", label: "Saved monthly on manual work" },
    ],
    features: [
      { num: "01", title: "Abandoned Cart Recovery", desc: "AI agents send personalised reminders, discounts, and follow-ups via email, SMS, and WhatsApp to bring back lost sales automatically -recovering 20-35% of abandoned carts." },
      { num: "02", title: "Inventory Synchronisation", desc: "Keep stock levels updated across Shopify, Amazon, WooCommerce, and other channels with real-time AI-driven sync -no manual updates, no overselling." },
      { num: "03", title: "Order Management", desc: "Automate order confirmations, shipping label generation, fulfilment routing, and status updates without any manual intervention from your team." },
      { num: "04", title: "Customer Support", desc: "Deploy AI chatbots to instantly answer product queries, shipping questions, and return requests 24/7 -resolving 70%+ of tickets without human input." },
      { num: "05", title: "Personalised Marketing", desc: "Use AI to segment customers and send tailored email, SMS, and WhatsApp campaigns based on purchase history and behaviour -boosting repeat sales." },
      { num: "06", title: "Product Recommendations", desc: "Automatically suggest related or trending products to every shopper to increase average order value and drive upsell revenue on autopilot." },
    ],
    benefits: [
      { title: "Higher Conversions", desc: "Recover lost carts, upsell effectively, and guide customers through faster purchase decisions with AI-personalised touchpoints.", icon: "📈" },
      { title: "Fewer Errors", desc: "Automation eliminates human mistakes in order processing, inventory updates, and refunds -keeping your operations accurate at scale.", icon: "✅" },
      { title: "Always-On Support", desc: "AI chatbots provide instant, round-the-clock service without additional staffing -cutting support costs by 60% or more.", icon: "💬" },
      { title: "Faster Growth", desc: "Scale operations and sales without increasing team size or overhead costs -automation grows with your store.", icon: "🚀" },
    ],
    technologies: ["n8n", "OpenAI", "Weaviate", "Shopify", "Mem0", "Odoo", "Apify", "WooCommerce", "Airtable"],
    useCases: ["Abandoned cart recovery sequences", "Multi-platform inventory sync", "Automated order fulfilment", "AI customer support chatbot", "Personalised email & SMS campaigns", "Product recommendation engine"],
    faqs: [
      { q: "What e-commerce processes can be automated with AI?", a: "Abandoned cart recovery, inventory sync, order management, personalised marketing, customer support, and product recommendations are the most impactful starting points." },
      { q: "How does AI help recover abandoned carts?", a: "AI sends personalised reminders, discounts, and follow-ups via email, SMS, or WhatsApp -recovering 20-35% of abandoned carts that would otherwise be lost." },
      { q: "Can AI manage inventory across multiple platforms?", a: "Yes. We build real-time inventory sync across Shopify, Amazon, WooCommerce, and other platforms so stock levels are always accurate everywhere." },
      { q: "Will automation integrate with my existing e-commerce platform?", a: "Absolutely. We integrate with Shopify, Magento, WooCommerce, BigCommerce, and even custom-built platforms." },
      { q: "How soon can businesses see ROI?", a: "Most stores see improvements in sales, fewer support tickets, and higher retention within 1-3 months of going live." },
      { q: "Can AI increase average order value?", a: "Yes -AI product recommendation engines suggest complementary products and bundles, increasing AOV by 10-25% on average." },
    ],
  },
  {
    slug: "ai-automation-in-retail",
    title: "Reimagine Retail with AI Automation",
    subtitle: "Retailers face pressure to reduce costs, manage inventory, and deliver seamless omnichannel experiences.",
    description:
      "Manual processes are no longer enough to compete in modern retail. AI automation helps you manage inventory intelligently, run loyalty programmes on autopilot, optimise staff schedules, and deliver consistent experiences across every channel -physical and digital.",
    heroTag: "Retail Automation",
    stats: [
      { value: "20%", label: "Inventory holding cost reduction" },
      { value: "15%", label: "Increase in repeat customers" },
      { value: "30%", label: "Faster checkout speed" },
      { value: "25%", label: "Improvement in staff productivity" },
    ],
    features: [
      { num: "01", title: "Inventory Replenishment", desc: "AI agents monitor stock levels and trigger reorders automatically to prevent stockouts and overstocking -so shelves are always right." },
      { num: "02", title: "POS & Billing Automation", desc: "Integrate AI with point-of-sale systems for automated discounts, loyalty points, receipts, and returns -reducing friction at every transaction." },
      { num: "03", title: "Customer Loyalty Programmes", desc: "Automate rewards, personalised offers, and customer reminders to boost retention -loyalty schemes that run without any manual management." },
      { num: "04", title: "Staff Scheduling", desc: "AI generates optimised staff rosters based on peak hours, sales trends, and staff availability -balancing cost and coverage automatically." },
      { num: "05", title: "Omnichannel Sync", desc: "Maintain consistent product, pricing, and promotional data across physical stores, mobile apps, and online platforms -one source of truth everywhere." },
      { num: "06", title: "Customer Feedback Analysis", desc: "AI processes reviews and feedback from every channel to identify improvement opportunities and flag issues before they damage your brand." },
    ],
    benefits: [
      { title: "Smarter Inventory", desc: "Reduce waste and prevent missed sales through demand-driven stock replenishment -always stocked for what's selling.", icon: "📦" },
      { title: "Faster Operations", desc: "Automated billing, loyalty management, and scheduling eliminate operational bottlenecks across every touchpoint.", icon: "⚡" },
      { title: "Enhanced Customer Experience", desc: "Personalised promotions and quicker service increase satisfaction and loyalty -customers keep coming back.", icon: "⭐" },
      { title: "Cost Savings", desc: "Optimise staffing, inventory, and marketing expenses through intelligent workflows -doing more with the same budget.", icon: "💰" },
    ],
    technologies: ["Gemini", "PineCone", "n8n", "Supabase", "Slack", "OpenAI", "Postgres", "Apify", "Odoo"],
    useCases: ["AI-driven inventory replenishment", "Automated POS & loyalty management", "Omnichannel product & pricing sync", "Staff schedule optimisation", "Customer feedback sentiment analysis", "Personalised promotional campaigns"],
    faqs: [
      { q: "What retail processes can be automated?", a: "Inventory replenishment, POS operations, loyalty programmes, staff scheduling, omnichannel syncing, and customer feedback analysis are the most valuable starting points." },
      { q: "How does automation improve inventory management?", a: "AI monitors stock, predicts demand, and automatically generates purchase orders to prevent overstocking or stockouts -keeping shelves optimised at all times." },
      { q: "Does automation integrate with existing POS systems?", a: "Yes. Workflows integrate seamlessly with POS systems, ERPs, and CRM platforms -we don't replace your stack, we connect and automate it." },
      { q: "How does AI enhance customer loyalty?", a: "AI tracks purchase behaviour and automates personalised offers, loyalty points, and reminder communications -keeping customers engaged without manual effort." },
      { q: "What ROI should retailers expect?", a: "Retailers typically see 15-25% inventory cost reduction and improved customer retention within the first year of deployment." },
      { q: "How long does implementation take?", a: "Most retail automation workflows launch within 4-6 weeks depending on integrations and store scale." },
    ],
  },
  {
    slug: "ai-automation-in-logistics",
    title: "Smarter Logistics with AI Automation",
    subtitle: "Customers expect real-time updates, flawless deliveries, and on-time arrivals. Manual processes create delays and rising costs.",
    description:
      "We build AI automation systems for logistics and freight companies that eliminate manual tracking updates, optimise routes in real time, auto-generate freight documentation, and keep customers informed at every stage -reducing costs and improving on-time delivery rates simultaneously.",
    heroTag: "Logistics Automation",
    stats: [
      { value: "28%", label: "Faster deliveries achieved" },
      { value: "25%", label: "Fuel & operating cost reduction" },
      { value: "45%", label: "Increase in customer satisfaction" },
      { value: "120+hrs", label: "Saved monthly on manual updates" },
    ],
    features: [
      { num: "01", title: "Claims & Dispute Resolution", desc: "AI filters, validates, and processes freight claims automatically -reducing backlogs, cutting resolution time, and flagging disputes before they escalate." },
      { num: "02", title: "Route & Load Optimisation", desc: "Analyses live traffic, weather, and delivery windows to generate optimal routes and load plans -reducing fuel costs and improving on-time rates." },
      { num: "03", title: "Freight Documentation", desc: "Auto-generates bills of lading, customs declarations, and compliance documents from shipment data -eliminating manual paperwork entirely." },
      { num: "04", title: "Driver & Fleet Performance Tracking", desc: "Automates driver scheduling, performance reporting, and maintenance alerts -keeping fleet operations running efficiently with minimal manual oversight." },
      { num: "05", title: "Real-Time Customer Notifications", desc: "Automated SMS and email updates at each shipment milestone -customers always know where their delivery is without calling your team." },
      { num: "06", title: "Digital Proof of Delivery", desc: "Instant capture, validation, and distribution of PODs at the point of delivery -eliminating paper, disputes, and delayed invoice cycles." },
    ],
    benefits: [
      { title: "On-Time Deliveries", desc: "AI route optimisation and proactive scheduling dramatically improve on-time delivery rates -boosting customer satisfaction scores.", icon: "🚚" },
      { title: "Lower Operational Costs", desc: "Automation of routing, documentation, and tracking reduces fuel spend and administrative overhead by 20-25%.", icon: "💰" },
      { title: "Better Customer Experience", desc: "Proactive shipment visibility and instant notifications keep customers informed -reducing inbound support calls.", icon: "📡" },
      { title: "Error-Free Operations", desc: "Automated documentation and POD capture eliminate the manual errors that cause payment disputes and compliance failures.", icon: "✅" },
    ],
    technologies: ["OpenAI", "Supabase", "n8n", "Gemini", "ChromaDB", "Slack", "Salesforce", "ElevenLabs", "Odoo"],
    useCases: ["Real-time shipment tracking automation", "AI route & load optimisation", "Freight documentation generation", "Driver scheduling & performance", "Customer delivery notifications", "Digital POD capture & validation"],
    faqs: [
      { q: "What logistics processes can be automated?", a: "Shipment tracking, route optimisation, freight documentation, fleet management, proof of delivery, claims processing, and customer notifications are all highly automatable." },
      { q: "How does route optimisation reduce costs?", a: "AI analyses live traffic, weather, delivery windows, and vehicle capacity to generate optimal routes -typically reducing fuel spend by 15-25%." },
      { q: "Can automation integrate with our TMS or WMS?", a: "Yes. We integrate with major TMS, WMS, ERP, and CRM platforms -our automations connect to your existing systems rather than replacing them." },
      { q: "How quickly can logistics automation be deployed?", a: "Most workflows go live within 4-8 weeks depending on integration complexity and the number of systems involved." },
      { q: "What ROI can we expect?", a: "Clients typically see 20-30% operational cost savings in the first year through reduced fuel spend, fewer manual processes, and lower error rates." },
      { q: "Can AI handle real-time shipment notifications to customers?", a: "Yes. We build automated notification workflows that trigger at each milestone -picked up, in transit, out for delivery, delivered -via SMS and email." },
    ],
  },
  {
    slug: "ai-automation-in-healthcare",
    title: "Revolutionize Healthcare with AI Automation",
    subtitle: "Healthcare teams manage high patient loads, extensive paperwork, and strict compliance requirements.",
    description:
      "AI automation frees healthcare staff to focus on better care. We build HIPAA-compliant automation systems that handle patient scheduling, EMR management, billing, and compliance reporting -reducing administrative burden, cutting errors, and improving patient satisfaction scores.",
    heroTag: "Healthcare Automation",
    stats: [
      { value: "40%", label: "Faster patient scheduling" },
      { value: "35%", label: "Reduction in admin errors" },
      { value: "30%", label: "Lower operational costs" },
      { value: "25%", label: "Improved patient satisfaction" },
    ],
    features: [
      { num: "01", title: "Patient Scheduling", desc: "AI automatically books, confirms, and reschedules patient appointments while sending reminders via SMS or email -reducing no-shows by 30-40%." },
      { num: "02", title: "Electronic Medical Records (EMR) Management", desc: "Automate data entry, record updates, and secure sharing of patient records across systems -keeping EMRs accurate without manual effort." },
      { num: "03", title: "Billing & Insurance Claims", desc: "AI extracts billing codes, validates claims, and automates submission to insurance providers -reducing denials and accelerating reimbursements." },
      { num: "04", title: "Telehealth Assistance", desc: "Automate patient intake forms, virtual appointment scheduling, and follow-up communication for telehealth workflows." },
      { num: "05", title: "Compliance & Reporting", desc: "Generate HIPAA-compliant reports, track audits, and ensure regulatory compliance automatically -with complete audit trails." },
      { num: "06", title: "Patient Communication", desc: "Deploy AI chatbots for FAQs, test results delivery, and medication reminders -keeping patients engaged and informed between visits." },
    ],
    benefits: [
      { title: "Better Patient Care", desc: "Free healthcare staff from administrative tasks so they can spend more time delivering care -the work that actually matters.", icon: "🏥" },
      { title: "Error Reduction", desc: "AI reduces errors in billing, scheduling, and record-keeping -minimising costly mistakes and claim rejections.", icon: "✅" },
      { title: "Cost Efficiency", desc: "Lower operational overhead with automated billing, claims, and reporting workflows -savings of 20-30% in admin costs.", icon: "💰" },
      { title: "Compliance Confidence", desc: "HIPAA and GDPR compliance through automated audit trails and secure data handling -always audit-ready.", icon: "🔐" },
    ],
    technologies: ["n8n", "OpenAI", "PineCone", "Veradigm", "Mem0", "Apify", "Vapi", "Athenahealth", "Cohere"],
    useCases: ["Patient appointment scheduling & reminders", "EMR data entry automation", "Insurance claims processing", "Telehealth intake & scheduling", "HIPAA compliance reporting", "Patient communication chatbots"],
    faqs: [
      { q: "What healthcare processes can AI automate?", a: "Patient scheduling, billing, insurance claims, EMR management, telehealth workflows, compliance reporting, and patient communication are all highly automatable." },
      { q: "Is AI automation secure for patient data?", a: "Yes. Our solutions comply with HIPAA, GDPR, and healthcare privacy standards -all data handling is encrypted and access-controlled." },
      { q: "Can automation work with our EMR/EHR system?", a: "Absolutely. We integrate with Epic, Cerner, Athenahealth, Allscripts, and custom EMR/EHR platforms." },
      { q: "Will automation replace doctors or nurses?", a: "No. Automation reduces administrative burden so healthcare professionals can spend more time on patient care -it supports staff, not replaces them." },
      { q: "How quickly can healthcare automation be deployed?", a: "Most workflows go live in 6-10 weeks depending on integrations and compliance requirements." },
      { q: "What ROI can healthcare providers expect?", a: "Clinics often save 20-30% in admin costs and see faster billing cycles and reduced claim rejections within the first year." },
    ],
  },
  {
    slug: "ai-automation-in-real-estate",
    title: "AI Automation for Real Estate Professionals",
    subtitle: "Real estate is moving faster than ever. Manual listings, endless paperwork, and slow follow-ups are costing you clients.",
    description:
      "We build AI automation systems for real estate agencies and property professionals -from instant lead capture and qualification to automated property matching, client communication workflows, and document processing. Close more deals without increasing headcount.",
    heroTag: "Real Estate Automation",
    stats: [
      { value: "40%", label: "Faster lead response time" },
      { value: "30%", label: "Increase in qualified leads" },
      { value: "25%", label: "Reduction in manual paperwork" },
      { value: "2×", label: "More deals closed" },
    ],
    features: [
      { num: "01", title: "Lead Capture & Qualification", desc: "AI agents automatically capture and qualify leads from property portals, your website, and social media -enriching each lead with contact and company data instantly." },
      { num: "02", title: "Property Listing Management", desc: "Sync listings across Zoopla, Rightmove, Zillow, and your website with current pricing and availability -one update propagates everywhere automatically." },
      { num: "03", title: "Client Communication Automation", desc: "Automate personalised email, WhatsApp, and SMS follow-ups throughout the client journey -from first enquiry to exchange and post-sale." },
      { num: "04", title: "Appointment Scheduling", desc: "AI handles property viewing scheduling, confirmation messages, reminders, and cancellations -eliminating the back-and-forth of manual coordination." },
      { num: "05", title: "Document Processing", desc: "Extract and organise data from contracts, agreements, and compliance documents automatically -speeding up transactions and reducing errors." },
      { num: "06", title: "Property Matching", desc: "Automatically match new listings to buyer profiles in your database and trigger personalised alerts -keeping your pipeline warm without manual effort." },
    ],
    benefits: [
      { title: "Close Deals Faster", desc: "Instant lead response and automated follow-up sequences mean fewer deals lost to slow reaction times -respond before competitors do.", icon: "🏡" },
      { title: "Streamlined Operations", desc: "Automated listing management, scheduling, and document workflows reduce the admin that eats into selling time.", icon: "⚙️" },
      { title: "Reduced Paperwork", desc: "AI document processing and digital signing workflows cut manual paperwork by 25% -transactions complete faster.", icon: "📄" },
      { title: "Better Client Experience", desc: "Personalised, timely communication throughout the buying journey builds trust and generates referrals.", icon: "⭐" },
    ],
    technologies: ["Zep", "n8n", "Postgres", "Supabase", "OpenAI", "Zoho", "ChromaDB", "HubSpot", "Salesforce"],
    useCases: ["Automated lead capture & CRM routing", "Multi-portal listing sync", "Viewing appointment scheduling", "Personalised client follow-up sequences", "Contract & document data extraction", "Property-to-buyer matching alerts"],
    faqs: [
      { q: "What real estate processes can AI automate?", a: "Lead capture and qualification, property listing management, client communication, viewing scheduling, document processing, and property-buyer matching are all prime automation targets." },
      { q: "How does automation improve lead management?", a: "AI instantly captures, enriches, and scores incoming leads -routing hot leads to the right agent with a full brief within seconds of enquiry." },
      { q: "Can automation keep listings updated across all portals?", a: "Yes. We build sync pipelines that push listing updates to all your portals simultaneously -price changes, availability, and new photos propagate instantly." },
      { q: "Which CRMs do you integrate with?", a: "We support HubSpot, Salesforce, Zoho CRM, Pipedrive, and most real estate-specific CRMs via API." },
      { q: "Is automation valuable for independent agents?", a: "Absolutely. Solo agents benefit most -automation handles the admin so they can focus entirely on client relationships and viewings." },
      { q: "How long does implementation take?", a: "Most real estate automation systems go live within 4-6 weeks depending on the number of platforms and integrations involved." },
    ],
  },
  {
    slug: "ai-automation-in-hospitality",
    title: "Deliver Exceptional Guest Experiences with AI",
    subtitle: "Hospitality businesses juggle countless moving parts. Manual processes mean slower service and missed revenue opportunities.",
    description:
      "From reservations to check-outs, we build AI automation systems for hotels, restaurants, and hospitality businesses that eliminate manual coordination -automating reservations, guest communication, staff scheduling, upselling, and feedback collection to deliver consistent, 5-star service at scale.",
    heroTag: "Hospitality Automation",
    stats: [
      { value: "25%", label: "Increase in guest satisfaction" },
      { value: "20%", label: "Reduction in operational costs" },
      { value: "30%", label: "Faster guest response time" },
      { value: "2×", label: "Improvement in staff efficiency" },
    ],
    features: [
      { num: "01", title: "Reservation Management", desc: "AI automatically confirms, modifies, and cancels bookings across your PMS, booking engine, and OTAs in real time -zero double-bookings, zero manual updates." },
      { num: "02", title: "Guest Communication", desc: "Automate pre-arrival messages, in-stay updates, and post-checkout follow-ups via email, SMS, or WhatsApp -personalised to each guest's profile and preferences." },
      { num: "03", title: "Staff Scheduling", desc: "AI creates optimised staff rosters based on guest volume, events, and service requirements -balancing labour costs with service quality automatically." },
      { num: "04", title: "Service Request Handling", desc: "Deploy AI to route guest service requests instantly to the right department and provide live status updates -guests and staff both stay informed." },
      { num: "05", title: "Feedback Collection & Analysis", desc: "Automatically gather post-stay reviews, analyse sentiments, and alert managers to negative feedback before it goes public -protecting your reputation." },
      { num: "06", title: "Upselling & Cross-Selling", desc: "AI suggests spa bookings, dining upgrades, or room enhancements based on guest profile and stay history -generating incremental revenue on autopilot." },
    ],
    benefits: [
      { title: "Better Guest Experience", desc: "Personalised communication and faster responses make guests feel genuinely valued throughout their stay -driving loyalty and return visits.", icon: "🏨" },
      { title: "Operational Efficiency", desc: "Automate bookings, scheduling, and follow-ups to save staff time and redirect effort toward delivering memorable experiences.", icon: "⚙️" },
      { title: "Revenue Growth", desc: "AI-powered upselling and cross-selling increase per-guest revenue without extra manual effort -every stay earns more.", icon: "💰" },
      { title: "Consistent Service", desc: "Automation ensures every guest receives timely, accurate, and high-quality service -regardless of occupancy levels or staff turnover.", icon: "✅" },
    ],
    technologies: ["Weaviate", "n8n", "Supabase", "Slack", "OpenAI", "Calendly", "Gemini", "HubSpot", "Odoo"],
    useCases: ["Multi-platform reservation sync", "Pre-arrival & in-stay guest messaging", "AI-powered upsell campaigns", "Staff roster optimisation", "Post-stay review collection", "Service request routing & tracking"],
    faqs: [
      { q: "What hospitality processes can be automated?", a: "Reservation management, guest communication, staff scheduling, service request handling, upselling, and feedback collection are the highest-impact automation areas." },
      { q: "How does automation improve guest satisfaction?", a: "AI ensures faster responses, personalised communication, and proactive service updates -making guests feel valued at every touchpoint." },
      { q: "Can automation integrate with our property management system?", a: "Yes. Workflows integrate with leading PMS platforms, booking engines, and OTAs -we connect your entire hospitality tech stack." },
      { q: "How does AI help with upselling?", a: "AI analyses guest profiles and recommends spa sessions, dining options, or room upgrades at optimal moments during the booking and in-stay journey." },
      { q: "Is automation useful for smaller hotels and guesthouses?", a: "Absolutely. Smaller operations benefit most -automation handles repetitive coordination so a small team can deliver large-hotel service quality." },
      { q: "How quickly can automation be implemented?", a: "Most hospitality workflows deploy within 4-6 weeks depending on property size and the number of systems that need to be integrated." },
    ],
  },
  {
    slug: "ai-automation-in-manufacturing",
    title: "AI Automation in Manufacturing",
    subtitle: "Manual processes slowing production? AI-powered automation streamlines operations, reduces errors, and gives you a competitive edge.",
    description:
      "We help manufacturers automate order management, inventory tracking, quality control, and supply chain workflows -boosting efficiency and accuracy while reducing costs. From order-to-production pipelines to predictive maintenance alerts, we build automations that keep your factory floor running at full capacity.",
    heroTag: "Manufacturing Automation",
    stats: [
      { value: "30%", label: "Faster production cycle times" },
      { value: "20%", label: "Reduction in inventory waste" },
      { value: "25%", label: "Decrease in quality defect rates" },
      { value: "40%", label: "Lower manual processing overhead" },
    ],
    features: [
      { num: "01", title: "Order-to-Production Workflow", desc: "Automate the entire cycle from order intake through production scheduling to shipping notifications -using AI agents and n8n to orchestrate every step." },
      { num: "02", title: "Inventory Management", desc: "AI-driven inventory optimisation that monitors stock levels, predicts demand, and triggers reorders automatically -preventing production stoppages." },
      { num: "03", title: "Quality Control Reporting", desc: "Automated defect analysis and quality report generation from production line data -catching issues early and reducing rework costs." },
      { num: "04", title: "Procurement & Supply Chain", desc: "Streamline supplier communications, purchase order generation, and delivery tracking -cutting procurement cycle times significantly." },
      { num: "05", title: "Machine Monitoring & Alerts", desc: "Predictive maintenance workflows that monitor equipment performance, detect anomalies, and notify technicians before breakdowns occur." },
      { num: "06", title: "Customer Communication", desc: "AI chatbots and voice assistants for 24/7 order status enquiries, delivery ETAs, and support -without tying up your operations team." },
    ],
    benefits: [
      { title: "Save Time & Reduce Errors", desc: "Automated order processing, inventory updates, and quality reporting eliminate the manual tasks that slow production and cause mistakes.", icon: "⚙️" },
      { title: "Scale Without Headcount", desc: "Handle more orders and production runs without adding admin staff -automation scales with your capacity.", icon: "📈" },
      { title: "Prevent Costly Downtime", desc: "Predictive maintenance alerts catch equipment issues before they cause production stoppages -protecting output and deadlines.", icon: "🔧" },
      { title: "Better Customer Experience", desc: "Instant, accurate order updates and AI support agents keep customers informed and satisfied throughout the production cycle.", icon: "⭐" },
    ],
    technologies: ["Supabase", "Odoo", "Slack", "OpenAI", "ChromaDB", "n8n", "Airtop", "Zoho", "HubSpot"],
    useCases: ["End-to-end order-to-production automation", "AI-driven inventory replenishment", "Quality control defect reporting", "Supplier & procurement workflows", "Predictive maintenance alerting", "Customer order status automation"],
    faqs: [
      { q: "What manufacturing processes can AI automate?", a: "Order workflows, inventory management, quality control reporting, procurement, predictive maintenance, compliance documentation, and customer communication are all strong candidates." },
      { q: "Can automation integrate with our ERP system?", a: "Yes. We integrate with SAP, Oracle, Odoo, Microsoft Dynamics, and custom ERP platforms -automations connect to your existing systems." },
      { q: "How does predictive maintenance automation work?", a: "Sensors and machine data feed into AI models that detect abnormal patterns. When an anomaly is detected, an alert is automatically sent to the relevant technician with a summary and recommended action." },
      { q: "What production speed improvement can we expect?", a: "Manufacturers typically see 20-30% production speed improvement through reduced manual coordination, faster order processing, and fewer stoppages." },
      { q: "Is automation suitable for small and mid-size manufacturers?", a: "Yes. SME manufacturers benefit significantly -automation reduces the admin burden on a small team and helps compete with larger operations." },
      { q: "What is the typical ROI timeline?", a: "Most manufacturers see measurable ROI within 6-12 months through reduced labour costs, lower error rates, and improved throughput." },
    ],
  },
  {
    slug: "ai-automation-in-insurance",
    title: "Revolutionize Insurance with AI Automation",
    subtitle: "Manual processes create delays, customer frustration, and fraud vulnerabilities. AI automation maintains operational excellence.",
    description:
      "We build AI automation systems for insurers that process claims faster, automate underwriting workflows, detect fraud in real time, and keep customers informed 24/7 -reducing operational costs by 25%+ while improving policyholder satisfaction and compliance confidence.",
    heroTag: "Insurance Automation",
    stats: [
      { value: "50%", label: "Faster claims processing" },
      { value: "35%", label: "Reduction in manual errors" },
      { value: "25%", label: "Lower operational costs" },
      { value: "30%", label: "Increase in customer retention" },
    ],
    features: [
      { num: "01", title: "Claims Processing", desc: "AI extracts claim document data, validates information, and automates approvals or escalations -reducing processing time from weeks to hours." },
      { num: "02", title: "Underwriting Automation", desc: "Analyses applicant profiles and third-party data to accelerate underwriting decisions -improving accuracy while cutting manual review time." },
      { num: "03", title: "Policy Administration", desc: "Automates policy creation, renewals, and cancellations with full system integration -ensuring accuracy and eliminating manual data entry." },
      { num: "04", title: "Fraud Detection", desc: "AI continuously monitors claims and applications to identify anomalies and flag suspicious cases before they result in payouts." },
      { num: "05", title: "Customer Support", desc: "AI chatbots handle FAQs, policy enquiries, renewal reminders, and claim status updates 24/7 -reducing inbound call volumes significantly." },
      { num: "06", title: "Regulatory Compliance", desc: "Automates compliance checks, reporting, and audit documentation -ensuring GDPR, HIPAA, and PCI-DSS compliance without manual effort." },
    ],
    benefits: [
      { title: "Faster Claims Settlement", desc: "AI-driven claims processing reduces settlement time from weeks to hours -improving customer satisfaction and NPS scores dramatically.", icon: "⚡" },
      { title: "Improved Accuracy", desc: "Eliminates manual data entry errors in claims, policies, and underwriting -reducing costly mistakes and compliance risks.", icon: "✅" },
      { title: "Fraud Prevention", desc: "Continuous AI monitoring for suspicious patterns in claims and applications protects against fraud before payouts are made.", icon: "🛡️" },
      { title: "Cost Savings", desc: "Automation lowers operational expenses across underwriting, claims handling, and support -typically 20-40% in the first year.", icon: "💰" },
    ],
    technologies: ["n8n", "PineCone", "Airtable", "OpenAI", "Twilio", "ChromaDB", "Slack", "Retell AI", "Mailchimp"],
    useCases: ["Automated claims intake & processing", "AI underwriting decision support", "Policy renewal automation", "Real-time fraud detection", "24/7 customer support chatbot", "Compliance audit documentation"],
    faqs: [
      { q: "What insurance processes can AI automate?", a: "Claims processing, underwriting, fraud detection, policy administration, renewals, and customer communications are all highly automatable." },
      { q: "How does AI accelerate claims processing?", a: "AI extracts claim data, validates against policy terms, and instantly approves straightforward claims while routing complex cases to human agents -with full context." },
      { q: "Can AI reduce insurance fraud?", a: "Yes. AI analyses claim patterns, applicant data, and historical fraud signals to flag suspicious activity before approvals -significantly reducing fraudulent payouts." },
      { q: "Is automation secure for sensitive customer data?", a: "Absolutely. We use encryption, role-based access controls, and comply with GDPR, HIPAA, and PCI-DSS standards across all workflows." },
      { q: "How does AI enhance underwriting?", a: "AI analyses applicant data, credit scores, and third-party sources to accelerate underwriting decisions -improving both speed and consistency." },
      { q: "How long does implementation take?", a: "Most insurance automation workflows deploy within 6-10 weeks depending on the complexity of integrations and compliance requirements." },
    ],
  },
  {
    slug: "ai-automation-in-recruitment",
    title: "Transform Recruitment with AI Automation",
    subtitle: "Recruiters spend countless hours screening resumes, scheduling interviews, and managing candidate communication.",
    description:
      "Manual hiring processes slow recruitment and cause loss of top talent. We build AI automation systems for recruiters and HR teams that handle candidate sourcing, resume screening, interview scheduling, and onboarding workflows -cutting time-to-hire by 50% while improving candidate experience.",
    heroTag: "Recruitment Automation",
    stats: [
      { value: "50%", label: "Faster time-to-hire" },
      { value: "35%", label: "Reduction in recruitment costs" },
      { value: "2×", label: "Improvement in candidate engagement" },
      { value: "60%", label: "Less time on manual screening" },
    ],
    features: [
      { num: "01", title: "Candidate Sourcing", desc: "AI scrapes job boards and databases to identify qualified candidates automatically -building a shortlist without hours of manual searching." },
      { num: "02", title: "Resume Screening", desc: "AI scans resumes, matches skills with job requirements, and ranks candidates for faster shortlisting -reducing screening time by 60%." },
      { num: "03", title: "Interview Scheduling", desc: "Automates scheduling, rescheduling, and interview reminders with calendar integration -eliminating the back-and-forth that delays hiring." },
      { num: "04", title: "Candidate Communication", desc: "AI chatbots handle FAQs, job status updates, and follow-ups automatically -keeping candidates engaged throughout the hiring journey." },
      { num: "05", title: "Background Verification", desc: "Automates document collection, verification, and compliance reporting -cutting days off the pre-employment check process." },
      { num: "06", title: "Onboarding Workflows", desc: "Automates offer letter generation, digital signatures, and new hire document collection -giving every new employee a smooth first-day experience." },
    ],
    benefits: [
      { title: "Faster Hiring", desc: "Automated screening and scheduling reduce time-to-hire dramatically -fill roles before competitors can even shortlist.", icon: "⚡" },
      { title: "Cost Savings", desc: "Eliminate repetitive tasks and optimise recruiter time -spending more hours on relationship-building and less on admin.", icon: "💰" },
      { title: "Better Candidate Experience", desc: "Instant updates, smooth scheduling, and proactive communication keep candidates engaged and improve offer acceptance rates.", icon: "🤝" },
      { title: "Data-Driven Hiring", desc: "AI tracks performance across hiring stages and sources -giving you insight into what's working and where to improve.", icon: "📊" },
    ],
    technologies: ["Eleven Labs", "OpenAI", "n8n", "Greenhouse", "Twilio", "Slack", "Lever", "Calendly", "Workday"],
    useCases: ["Automated candidate sourcing", "AI resume screening & ranking", "Interview scheduling automation", "Candidate status communication", "Background verification workflows", "Digital onboarding & e-signatures"],
    faqs: [
      { q: "What recruitment processes can be automated?", a: "Candidate sourcing, resume screening, interview scheduling, candidate communication, background verification, and onboarding are all excellent automation targets." },
      { q: "How does AI improve resume screening?", a: "AI scans resumes, matches skills with job descriptions, and ranks candidates for faster, more consistent shortlisting -reducing bias and time simultaneously." },
      { q: "Can automation integrate with our ATS or HR software?", a: "Yes. We integrate with Greenhouse, Lever, Workday, SAP SuccessFactors, and custom platforms -connecting your existing tools rather than replacing them." },
      { q: "Will automation replace recruiters?", a: "No. Automation handles administrative tasks so recruiters can focus on relationship-building, candidate experience, and final hiring decisions." },
      { q: "How does automation improve candidate engagement?", a: "AI ensures candidates receive instant status updates, reminders, and personalised communication throughout the hiring process -reducing drop-off at every stage." },
      { q: "What ROI can automation deliver?", a: "Organisations typically reduce hiring costs by 20-35% and fill roles significantly faster -improving both efficiency and quality of hire." },
    ],
  },
];

export function getIndustryBySlug(slug: string): IndustryData | undefined {
  return industries.find((i) => i.slug === slug);
}
